number = 4
number2 = 3
number3 = number + number2
print(f"Addition  of ({number} + {number2}) = : {number3}")
number3 = number - number2
print(f"Subtraction  of ({number} - {number2}) = : {number3}")
number3 = number * number2
print(f"Multiplication  of ({number} * {number2}) = : {number3}")
number3 = number / number2
print(f"True Division  of ({number} / {number2}) = : {number3}")
number3 = number // number2
print(f"Floor Division  of ({number} // {number2}) = : {number3}")
number3 = number % number2
print(f"Modulo Division (Remainder)  of ({number} % {number2}) = : {number3}")
number3 = number ** number2
print(f"Exponent of ({number} ** {number2}) = : {number3}")